coverage:
  status:
    project:
      default: off
      tests:
        flags: tests
      documentation:
        flags: documentation
        target: 80%
flags:
  tests:
    - include/
    - src/
  documentation:
    - include/
    - src/
