language: cpp

sudo: reguired
dist: trusty

env:
  global:
    - CTEST_EXT_COLOR_OUTPUT=TRUE
    - CTEST_BUILD_FLAGS=-j4

matrix:
        include:
                - os: linux
                  compiler: gcc
                  env: CTEST_TARGET_SYSTEM=Linux-gcc CTEST_MODEL=Nightly COMPILER=g++-4.9
                  addons:
                          apt:
                                  sources:
                                          - ubuntu-toolchain-r-test
                                  packages:
                                          - valgrind
                                          - g++-4.9
                                          - gcc-4.9
                                          - lcov
                                          - python3
                                          - doxygen
                          code_climate:
                                 repo_token: 54bb6b4e88c97d912140ca77ed5660a7df0da72ea5385f222ed55cd0970dce2f
                                 
                  before_install:
                          - sudo apt-get -qq update
                          - sudo apt-get install -y libboost1.55-dev 
                            # make sure CXX is correctly set
                          - if [[ "${COMPILER}" != "" ]]; then export CXX=${COMPILER}; fi

script: 
                          - uname -a
                          - $CXX --version
                          - python --version
                          - mkdir build && cd build 
                          - python -m pip install coverxygen
                          - cmake -DCMAKE_BUILD_TYPE=Coverage .. 
                          - make codecov_test 
                          - ctest -V -D Experimental
                          - make codecov_doc
                          - cd ..
