language: cpp

sudo: reguired
dist: trusty

env:
  global:
    - CTEST_EXT_COLOR_OUTPUT=TRUE
    - CTEST_BUILD_FLAGS=-j4

matrix:
        include:
                - os: linux
                  compiler: gcc
                  env: CTEST_TARGET_SYSTEM=Linux-gcc CTEST_MODEL=Nightly COMPILER=g++-4.9
                  addons:
                          apt:
                                  sources:
                                          - ubuntu-toolchain-r-test
                                  packages:
                                          - valgrind
                                          - g++-4.9
                  before_install:
                          - sudo apt-get -qq update
                          - sudo apt-get install -y libboost1.55-dev 
                            # make sure CXX is correctly set
                          - if [[ "${COMPILER}" != "" ]]; then export CXX=${COMPILER}; fi

script: 
                          - uname -a
                          - $CXX --version
                          - mkdir build && cd build 
                          - cmake .. 
                          - cmake --build . 
                          - ctest -V
                          - cd ..
