language: cpp

sudo: reguired
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - valgrind
      - g++-4.9

env:
  global:
    - CTEST_EXT_COLOR_OUTPUT=TRUE
    - CTEST_BUILD_FLAGS=-j4

matrix:
        include:
                - os: linux
                  compiler: gcc
                  env: CTEST_TARGET_SYSTEM=Linux-gcc CTEST_MODEL=Nightly COMPILER=g++-4.9

                  before_install:
                          - sudo apt-get -qq update
                          - sudo apt-get install -y libboost1.55-dev 
                - os: osx
                  compiler: clang
                  env: CTEST_TARGET_SYSTEM=MacOS-clang CTEST_MODEL=Nightly COMPILER=g++-4.9
                  before_install:
                          - brew update
                          - brew install boost

script: mkdir build && cd build && cmake ../ && make && make test
