language: cpp

sudo: reguired
dist: trusty

addons:
  apt:
    packages:
      - valgrind

env:
  global:
    - CTEST_EXT_COLOR_OUTPUT=TRUE
    - CTEST_BUILD_FLAGS=-j4

matrix:
        include:
                - os: linux
                  compiler: gcc
                  env: CTEST_TARGET_SYSTEM=Linux-gcc    CTEST_MODEL=Nightly
                - os: windows
                  compiler: gcc
                  env: CTEST_TARGET_SYSTEM=Windows-gcc  CTEST_MODEL=Nightly

script: mkdir build && cd build && cmake ../ && make && make test
