language: cpp

sudo: reguired
dist: trusty

env:
  global:
    - CTEST_EXT_COLOR_OUTPUT=TRUE
    - CTEST_BUILD_FLAGS=-j4

matrix:
        include:
                - os: linux
                  compiler: gcc
                  env: CTEST_TARGET_SYSTEM=Linux-gcc CTEST_MODEL=Nightly COMPILER=g++-4.9
                  addons:
                          apt:
                                  sources:
                                          - ubuntu-toolchain-r-test
                                  packages:
                                          - valgrind
                                          - g++-4.9
                                          - gcc-4.9
                                          - lcov
                                          - python3
                                          - python3-pip
                                          - doxygen
                                          - cppcheck
                                          - docker
                          code_climate:
                                 repo_token: 54bb6b4e88c97d912140ca77ed5660a7df0da72ea5385f222ed55cd0970dce2f

                  before_install:
                          - sudo apt-get -qq update
                          - sudo apt-get install -y libboost1.55-dev
                            # make sure CXX is correctly set
                          - if [[ "${COMPILER}" != "" ]]; then export CXX=${COMPILER}; fi
                          - sudo python3 -m pip install coverxygen
                          - sudo docker pull codeclimate/codeclimate
                          - git clone https://github.com/antiagainst/codeclimate-cppcheck.git
                          - cd codeclimate-cppcheck && sudo docker build -t codeclimate/codeclimate-cppcheck . && cd ..


script:
                          - uname -a
                          - $CXX --version
                          - python3 --version
                          - mkdir build && cd build
                          - cmake -DCMAKE_BUILD_TYPE=Debug ..
                          - make test
after_script:
                          - cmake -DCMAKE_BUILD_TYPE=Coverage ..
                          - make codecov_test
                          - ctest -V -D Experimental
                          - make codecov_doc
                          - codeclimate engines:enable cppcheck
                          - cd .. && codeclimate analyze
